apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nginx-route
  namespace: dev
spec:
  parentRefs:
    - name: dev-gateway
      namespace: dev
  # hostnames:
  #   - nginx.dev.nasirtechtalks.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: nginx-svc
          port: 80