apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: frontend-route
  namespace: dev
spec:
  parentRefs:
    - name: traefik-gateway   # Must match your Gateway
      namespace: dev
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: schoolmnmfe
          port: 80
    - matches:
        - path:
            type: PathPrefix
            value: /std
      backendRefs:
        - name: studentservice
          port: 80
    - matches:
        - path:
            type: PathPrefix
            value: /tech
      backendRefs:
        - name: teachersservice
          port: 80
    - matches:
        - path:
            type: PathPrefix
            value: /emp
      backendRefs:
        - name: employeeservice
          port: 80

