apiVersion: apps/v1
kind: Deployment
metadata:
  name: studentservice
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: studentservice
  template:
    metadata:
      labels:
        app: studentservice
    spec:
      containers:
        - name: studentservice
          image: nasirnjs/gostudentsvc:0.0.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5001
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: app-mongo-secret
                  key: MONGODB_URI
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: app-mongo-secret
                  key: DATABASE_NAME
