apiVersion: apps/v1
kind: Deployment
metadata:
  name: schoolmnmfe
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: schoolmnmfe
  template:
    metadata:
      labels:
        app: schoolmnmfe
    spec:
      containers:
        - name: schoolmnmfe
          image: nasirnjs/schaoolmnmfe:0.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80