apiVersion: apps/v1
kind: Deployment
metadata:
  name: schoolmnmfe
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: schoolmnmfe
  template:
    metadata:
      labels:
        app: schoolmnmfe
    spec:
      containers:
        - name: schoolmnmfe
          image: nasirnjs/schaoolmnmfe:0.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: app-mongo-secret
                  key: MONGODB_URI
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: app-mongo-secret
                  key: DATABASE_NAME
