apiVersion: apps/v1
kind: Deployment
metadata:
  name: employeeservice
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: employeeservice
  template:
    metadata:
      labels:
        app: employeeservice
    spec:
      containers:
        - name: employeeservice
          image: nasirnjs/goemployeesvc:0.0.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5003
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: app-mongo-secret
                  key: MONGODB_URI
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: app-mongo-secret
                  key: DATABASE_NAME
